name: build and release

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: install dependencies
        run: bun install

      - name: build (checks build errors early)
        run: bun run build

      - name: run tests and (implicit) coverage
        run: bun test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: install dependencies
        run: bun install

      - name: build
        run: bun run build

      - name: run tests and (implicit) coverage
        run: bun test

      - name: publish to npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        run: bun publish --access public
